name: Maven Package

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: my-app

    - name: Publish to GitHub Packages
      run: |
        mvn -Papache-release package verify deploy \
        -DskipTests=true \
        -DaltStagingDirectory=local-staging \
        -DskipRemoteStaging=true \
        -DserverId=github \
        -s settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: my-app

    - name: Upload local staging directory
      uses: actions/upload-artifact@v3
      with:
        name: local-staging
        path: my-app/local-staging
        if-no-files-found: error
