name: Setup Nexus Repository

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nexus Repository
        run: ./setup-nexus.sh

      - name: Local staging
        working-directory: ./my-app
        shell: bash
        run: |
          mvn package verify org.sonatype.plugins:nexus-staging-maven-plugin:deploy \
            -DskipTests=true \
            -DaltStagingDirectory=local-staging \
            -DskipRemoteStaging=true \
            -DserverId=nexus \
            -DnexusUrl=http://localhost:8081/
            -DaltDeploymentRepository=nexus::default::http://localhost:8081/repository/maven-releases/ 