name: Setup Nexus Repository

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nexus Repository
        run: ./setup-nexus.sh

      - name: Build and Deploy Maven Project
        run: mvn clean deploy -s ./settings.xml
        working-directory: ./my-app