name: Setup Nexus Repository

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nexus Repository
        run: ./setup-nexus.sh

      - name: Local staging
        working-directory: ./my-app
        shell: bash
        run: |
          mvn clean package verify org.sonatype.plugins:nexus-staging-maven-plugin:deploy \
            -DskipTests=true \
            -DaltStagingDirectory=local-staging \
            -DskipRemoteStaging=true \
      - name: Upload local staging directory
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.classifier }}-local-staging
          path: my-app/local-staging
          if-no-files-found: error
